# Builder for Session 6, solutions.ipynb (answer key).
# Runnable, verified solutions for all 12 Exercises and 8 Code Challenges.
import nbformat as nbf
from nbformat.v4 import new_notebook, new_code_cell, new_markdown_cell

cells = []
def md(t):   cells.append(new_markdown_cell(t))
def code(t): cells.append(new_code_cell(t))

md('<div style="background:#1e1e2e; padding:16px 20px; border-radius:8px; font-family:monospace; '
   'color:#cdd6f4; line-height:1.8">'
   '<p style="margin:0 0 8px 0; color:#cba6f7; font-weight:bold; font-size:1.05em;">✅ Session 6 — Decorators · Solutions</p>'
   '<p style="margin:0;">Worked, runnable solutions for the 12 <strong>Exercises</strong> and 8 '
   '<strong>Code Challenges</strong>. Run top to bottom to verify. Try them in '
   '<code>01_decorators.ipynb</code> first.</p></div>')

md("### Exercises — Solutions")

code('import functools, inspect, time\n'
    'from functools import wraps')
code('# E1 (Easy) — logged\n'
    'def logged(fn):\n'
    '    @wraps(fn)\n'
    '    def w(*a, **k):\n'
    '        print("calling", fn.__name__)\n'
    '        return fn(*a, **k)\n'
    '    return w\n\n'
    '@logged\n'
    'def add(a, b): return a + b\n'
    'print(add(2, 3))                       # calling add \\n 5')
code('# E2 (Easy) — @functools.wraps preserves metadata\n'
    'def deco(fn):\n'
    '    @wraps(fn)\n'
    '    def w(*a, **k): return fn(*a, **k)\n'
    '    return w\n\n'
    '@deco\n'
    'def greet():\n'
    '    "Say hi."\n'
    '    return "hi"\n'
    'print(greet.__name__, "|", greet.__doc__)   # greet | Say hi.')
code('# E3 (Easy) — debug: print args and result\n'
    'def debug(fn):\n'
    '    @wraps(fn)\n'
    '    def w(*a, **k):\n'
    '        r = fn(*a, **k)\n'
    '        print(f"{fn.__name__}{a} -> {r}")\n'
    '        return r\n'
    '    return w\n\n'
    '@debug\n'
    'def mul(a, b): return a * b\n'
    'print(mul(3, 4))                       # mul(3, 4) -> 12 \\n 12')
code('# E4 (Med) — timer (timing varies, so not asserted)\n'
    'def timer(fn):\n'
    '    @wraps(fn)\n'
    '    def w(*a, **k):\n'
    '        start = time.perf_counter()\n'
    '        r = fn(*a, **k)\n'
    '        print(f"{fn.__name__} took ~{(time.perf_counter()-start)*1000:.2f}ms")\n'
    '        return r\n'
    '    return w\n\n'
    '@timer\n'
    'def work(): return sum(range(100000))\n'
    'print(work())')
code('# E5 (Med) — collect(n): return the LIST of all n results\n'
    'def collect(n):\n'
    '    def d(fn):\n'
    '        @wraps(fn)\n'
    '        def w(*a, **k): return [fn(*a, **k) for _ in range(n)]\n'
    '        return w\n'
    '    return d\n\n'
    'c = [0]\n'
    '@collect(3)\n'
    'def tick():\n'
    '    c[0] += 1; return c[0]\n'
    'print(tick())                          # [1, 2, 3]')
code('# E6 (Med) — default_on_error(default)\n'
    'def default_on_error(default):\n'
    '    def d(fn):\n'
    '        @wraps(fn)\n'
    '        def w(*a, **k):\n'
    '            try: return fn(*a, **k)\n'
    '            except Exception: return default\n'
    '        return w\n'
    '    return d\n\n'
    '@default_on_error(-1)\n'
    'def div(a, b): return a // b\n'
    'print(div(10, 2), div(10, 0))          # 5 -1')
code('# E7 (Med) — memoize (compare with functools.lru_cache)\n'
    'def memoize(fn):\n'
    '    cache = {}\n'
    '    @wraps(fn)\n'
    '    def w(*a):\n'
    '        if a not in cache: cache[a] = fn(*a)\n'
    '        return cache[a]\n'
    '    return w\n\n'
    '@memoize\n'
    'def sq(x): return x * x\n'
    'print(sq(5), sq(5))                    # 25 25 (2nd from cache)')
code('# E8 (Med) — require_nonneg\n'
    'def require_nonneg(fn):\n'
    '    @wraps(fn)\n'
    '    def w(*a, **k):\n'
    '        for v in a:\n'
    '            if isinstance(v, (int, float)) and v < 0:\n'
    '                raise ValueError("negative arg")\n'
    '        return fn(*a, **k)\n'
    '    return w\n\n'
    '@require_nonneg\n'
    'def s(a, b): return a + b\n'
    'print(s(2, 3))                         # 5\n'
    'try: s(-1, 3)\n'
    'except ValueError as e: print("raised:", e)')
code('# E9 (Hard) — count_calls: expose fn.calls\n'
    'def count_calls(fn):\n'
    '    @wraps(fn)\n'
    '    def w(*a, **k):\n'
    '        w.calls += 1\n'
    '        return fn(*a, **k)\n'
    '    w.calls = 0\n'
    '    return w\n\n'
    '@count_calls\n'
    'def h(): return 1\n'
    'h(); h()\n'
    'print(h.calls)                         # 2')
code('# E10 (Hard) — Memoize: class-based caching decorator with .cache\n'
    'class Memoize:\n'
    '    def __init__(self, fn):\n'
    '        self.fn = fn\n'
    '        self.cache = {}\n'
    '        functools.update_wrapper(self, fn)\n'
    '    def __call__(self, *a):\n'
    '        if a not in self.cache:\n'
    '            self.cache[a] = self.fn(*a)\n'
    '        return self.cache[a]\n\n'
    '@Memoize\n'
    'def sq(x): return x * x\n'
    'sq(4); sq(4)\n'
    'print(sq(4), sq.cache)                 # 16 {(4,): 16}')
code('# E11 (Hard) — tag(*labels): attach fn.tags, return fn unchanged\n'
    'def tag(*labels):\n'
    '    def d(fn):\n'
    '        fn.tags = labels\n'
    '        return fn\n'
    '    return d\n\n'
    '@tag("math", "fast")\n'
    'def add(a, b): return a + b\n'
    'print(add.tags, add(2, 3))             # (\'math\', \'fast\') 5')
code('# E12 (Hard) — validate_types: enforce parameter annotations at call time\n'
    'def validate_types(fn):\n'
    '    sig = inspect.signature(fn)\n'
    '    @wraps(fn)\n'
    '    def w(*a, **k):\n'
    '        bound = sig.bind(*a, **k)\n'
    '        for name, val in bound.arguments.items():\n'
    '            ann = fn.__annotations__.get(name)\n'
    '            if ann and not isinstance(val, ann):\n'
    '                raise TypeError(f"{name} must be {ann.__name__}")\n'
    '        return fn(*a, **k)\n'
    '    return w\n\n'
    '@validate_types\n'
    'def addt(a: int, b: int) -> int: return a + b\n'
    'print(addt(2, 3))                      # 5\n'
    'try: addt(2, "x")\n'
    'except TypeError as e: print("raised:", e)')

md("### Code Challenges — Solutions")

code('# C1 (Easy) — uppercase(fn)\n'
    'def uppercase(fn):\n'
    '    @wraps(fn)\n'
    '    def w(*a, **k): return fn(*a, **k).upper()\n'
    '    return w\n\n'
    '@uppercase\n'
    'def greet(n): return f"hi {n}"\n'
    'print(greet("bob"))                    # HI BOB')
code('# C2 (Easy) — add_prefix(prefix)\n'
    'def add_prefix(prefix):\n'
    '    def d(fn):\n'
    '        @wraps(fn)\n'
    '        def w(*a, **k): return prefix + fn(*a, **k)\n'
    '        return w\n'
    '    return d\n\n'
    '@add_prefix(">> ")\n'
    'def msg(): return "go"\n'
    'print(msg())                           # >> go')
code('# C3 (Med) — call_limit(n)\n'
    'def call_limit(n):\n'
    '    def d(fn):\n'
    '        calls = 0\n'
    '        @wraps(fn)\n'
    '        def w(*a, **k):\n'
    '            nonlocal calls\n'
    '            if calls >= n: raise RuntimeError("call limit exceeded")\n'
    '            calls += 1\n'
    '            return fn(*a, **k)\n'
    '        return w\n'
    '    return d\n\n'
    '@call_limit(2)\n'
    'def ping(): return "pong"\n'
    'print(ping(), ping())                  # pong pong\n'
    'try: ping()\n'
    'except RuntimeError as e: print("raised:", e)')
code('# C4 (Med) — audit(fn) -> fn.log\n'
    'def audit(fn):\n'
    '    @wraps(fn)\n'
    '    def w(*a, **k):\n'
    '        r = fn(*a, **k)\n'
    '        w.log.append((a, r))\n'
    '        return r\n'
    '    w.log = []\n'
    '    return w\n\n'
    '@audit\n'
    'def add(a, b): return a + b\n'
    'add(1, 2); add(3, 4)\n'
    'print(add.log)                         # [((1, 2), 3), ((3, 4), 7)]')
code('# C5 (Med) — enforce_return_type(t)\n'
    'def enforce_return_type(t):\n'
    '    def d(fn):\n'
    '        @wraps(fn)\n'
    '        def w(*a, **k):\n'
    '            r = fn(*a, **k)\n'
    '            if not isinstance(r, t):\n'
    '                raise TypeError(f"return must be {t.__name__}")\n'
    '            return r\n'
    '        return w\n'
    '    return d\n\n'
    '@enforce_return_type(int)\n'
    'def dbl(x): return x * 2\n'
    'print(dbl(3))                          # 6\n'
    '@enforce_return_type(int)\n'
    'def bad(): return "oops"\n'
    'try: bad()\n'
    'except TypeError as e: print("raised:", e)')
code('# C6 (Med) — ignore_exceptions(*excs)\n'
    'def ignore_exceptions(*excs):\n'
    '    def d(fn):\n'
    '        @wraps(fn)\n'
    '        def w(*a, **k):\n'
    '            try: return fn(*a, **k)\n'
    '            except excs: return None\n'
    '        return w\n'
    '    return d\n\n'
    '@ignore_exceptions(ValueError)\n'
    'def parse(x): return int(x)\n'
    'print(parse("5"), parse("abc"))        # 5 None (ValueError swallowed)\n'
    '@ignore_exceptions(ValueError)\n'
    'def only_value(): raise TypeError("nope")\n'
    'try: only_value()                      # TypeError NOT swallowed -> propagates\n'
    'except TypeError as e: print("propagated:", e)')
code('# C7 (Hard) — memoize_full: cache keyed by args AND kwargs\n'
    'def memoize_full(fn):\n'
    '    cache = {}\n'
    '    @wraps(fn)\n'
    '    def w(*a, **k):\n'
    '        key = (a, frozenset(k.items()))   # frozenset makes kwargs hashable (2C)\n'
    '        if key not in cache: cache[key] = fn(*a, **k)\n'
    '        return cache[key]\n'
    '    return w\n\n'
    'calls = []\n'
    '@memoize_full\n'
    'def combine(a, b=0):\n'
    '    calls.append((a, b)); return a + b\n'
    'print(combine(1, b=2), combine(1, b=2), combine(5), "| computed", len(calls))   # 3 3 5 | computed 2')
code('# C8 (Hard) — smart: works as @smart AND @smart(prefix=...)\n'
    'def smart(fn=None, *, prefix=">>"):\n'
    '    def decorator(f):\n'
    '        @wraps(f)\n'
    '        def w(*a, **k): return prefix + str(f(*a, **k))\n'
    '        return w\n'
    '    return decorator if fn is None else decorator(fn)\n\n'
    '@smart\n'
    'def a(): return "x"\n'
    '@smart(prefix="!! ")\n'
    'def b(): return "y"\n'
    'print(a(), "|", b())                   # >>x | !! y')

nb = new_notebook(cells=cells)
nb.metadata["kernelspec"] = {"display_name": "Python 3", "language": "python", "name": "python3"}
nb.metadata["language_info"] = {"name": "python"}
nbf.write(nb, "solutions.ipynb")
print("wrote solutions.ipynb with", len(cells), "cells")
