# Builder for Session 7D, solutions.ipynb (answer key).
# Runnable, verified solutions for all 12 Exercises and 8 Code Challenges.
import nbformat as nbf
from nbformat.v4 import new_notebook, new_code_cell, new_markdown_cell

cells = []
def md(t):   cells.append(new_markdown_cell(t))
def code(t): cells.append(new_code_cell(t))

md('<div style="background:#1e1e2e; padding:16px 20px; border-radius:8px; font-family:monospace; '
   'color:#cdd6f4; line-height:1.8">'
   '<p style="margin:0 0 8px 0; color:#cba6f7; font-weight:bold; font-size:1.05em;">✅ Session 7D — Properties &amp; Methods · Solutions</p>'
   '<p style="margin:0;">Worked, runnable solutions for the 12 <strong>Exercises</strong> and 8 '
   '<strong>Code Challenges</strong>. Run top to bottom to verify. Try them in '
   '<code>01_properties.ipynb</code> first.</p></div>')

md("### Exercises — Solutions")
code('import math\n'
    'from functools import cached_property')
code('# E1 — Rectangle read-only area\n'
    'class Rectangle:\n'
    '    def __init__(self, w, h): self.w = w; self.h = h\n'
    '    @property\n'
    '    def area(self): return self.w * self.h\n\n'
    'print(Rectangle(3, 4).area)           # 12')
code('# E2 — Person full_name\n'
    'class Person:\n'
    '    def __init__(self, first, last): self.first = first; self.last = last\n'
    '    @property\n'
    '    def full_name(self): return f"{self.first} {self.last}"\n\n'
    'print(Person("Siva", "N").full_name)')
code('# E3 — Circle diameter (read-only)\n'
    'class Circle:\n'
    '    def __init__(self, r): self.radius = r\n'
    '    @property\n'
    '    def diameter(self): return self.radius * 2\n\n'
    'print(Circle(5).diameter)             # 10')
code('# E4 — Age validated setter\n'
    'class Age:\n'
    '    def __init__(self, years): self.years = years\n'
    '    @property\n'
    '    def years(self): return self._years\n'
    '    @years.setter\n'
    '    def years(self, v):\n'
    '        if v < 0: raise ValueError("negative age")\n'
    '        self._years = v\n\n'
    'a = Age(30); print(a.years)\n'
    'try: Age(-1)\n'
    'except ValueError as e: print("raised:", e)')
code('# E5 — Grade clamped/validated 0-100\n'
    'class Grade:\n'
    '    def __init__(self, score): self.score = score\n'
    '    @property\n'
    '    def score(self): return self._score\n'
    '    @score.setter\n'
    '    def score(self, v):\n'
    '        if not 0 <= v <= 100: raise ValueError("0-100 only")\n'
    '        self._score = v\n\n'
    'print(Grade(85).score)\n'
    'try: Grade(150)\n'
    'except ValueError as e: print("raised:", e)')
code('# E6 — Money read-only dollars\n'
    'class Money:\n'
    '    def __init__(self, cents): self.cents = cents\n'
    '    @property\n'
    '    def dollars(self): return self.cents / 100\n\n'
    'print(Money(250).dollars)             # 2.5')
code('# E7 — Point.from_tuple classmethod\n'
    'class Point:\n'
    '    def __init__(self, x, y): self.x = x; self.y = y\n'
    '    @classmethod\n'
    '    def from_tuple(cls, t): return cls(t[0], t[1])\n\n'
    'p = Point.from_tuple((3, 4)); print(p.x, p.y)   # 3 4')
code('# E8 — Color.from_hex classmethod\n'
    'class Color:\n'
    '    def __init__(self, r, g, b): self.r = r; self.g = g; self.b = b\n'
    '    def __repr__(self): return f"Color({self.r}, {self.g}, {self.b})"\n'
    '    @classmethod\n'
    '    def from_hex(cls, h):\n'
    '        h = h.lstrip("#")\n'
    '        return cls(int(h[0:2],16), int(h[2:4],16), int(h[4:6],16))\n\n'
    'print(Color.from_hex("#ff0080"))      # Color(255, 0, 128)')
code('# E9 — TextUtils.word_count staticmethod\n'
    'class TextUtils:\n'
    '    @staticmethod\n'
    '    def word_count(s): return len(s.split())\n\n'
    'print(TextUtils.word_count("a b c d"))   # 4')
code('# E10 — BankAccount: validated property + methods + from_dict\n'
    'class BankAccount:\n'
    '    def __init__(self, balance=0): self.balance = balance\n'
    '    @property\n'
    '    def balance(self): return self._balance\n'
    '    @balance.setter\n'
    '    def balance(self, v):\n'
    '        if v < 0: raise ValueError("negative")\n'
    '        self._balance = v\n'
    '    def deposit(self, amt): self.balance += amt\n'
    '    def withdraw(self, amt):\n'
    '        if amt > self.balance: raise ValueError("insufficient")\n'
    '        self.balance -= amt\n'
    '    @classmethod\n'
    '    def from_dict(cls, d): return cls(d["balance"])\n\n'
    'a = BankAccount.from_dict({"balance": 100}); a.deposit(50)\n'
    'print(a.balance)                      # 150\n'
    'try: a.withdraw(500)\n'
    'except ValueError as e: print("raised:", e)')
code('# E11 — Vector2D with __slots__\n'
    'class Vector2D:\n'
    '    __slots__ = ("x", "y")\n'
    '    def __init__(self, x, y): self.x = x; self.y = y\n\n'
    'v = Vector2D(1, 2)\n'
    'print(hasattr(v, "__dict__"))         # False\n'
    'try: v.z = 3\n'
    'except AttributeError as e: print("raised:", e)')
code('# E12 — Temperature: two linked read-write properties\n'
    'class Temperature:\n'
    '    def __init__(self, celsius=0): self._celsius = celsius\n'
    '    @property\n'
    '    def celsius(self): return self._celsius\n'
    '    @celsius.setter\n'
    '    def celsius(self, v): self._celsius = v\n'
    '    @property\n'
    '    def fahrenheit(self): return self._celsius * 9/5 + 32\n'
    '    @fahrenheit.setter\n'
    '    def fahrenheit(self, v): self._celsius = (v - 32) * 5/9\n\n'
    't = Temperature(0)\n'
    'print(t.fahrenheit)                   # 32.0\n'
    't.fahrenheit = 212\n'
    'print(t.celsius)                      # 100.0')

md("### Code Challenges — Solutions")
code('# C1 — Employee annual\n'
    'class Employee:\n'
    '    def __init__(self, monthly): self.monthly = monthly\n'
    '    @property\n'
    '    def annual(self): return self.monthly * 12\n\n'
    'print(Employee(1000).annual)          # 12000')
code('# C2 — Duration.from_minutes\n'
    'class Duration:\n'
    '    def __init__(self, seconds): self.seconds = seconds\n'
    '    @classmethod\n'
    '    def from_minutes(cls, m): return cls(m * 60)\n\n'
    'print(Duration.from_minutes(2).seconds)   # 120')
code('# C3 — Email validated setter\n'
    'class Email:\n'
    '    def __init__(self, addr): self.addr = addr\n'
    '    @property\n'
    '    def addr(self): return self._addr\n'
    '    @addr.setter\n'
    '    def addr(self, v):\n'
    '        if "@" not in v: raise ValueError("invalid email")\n'
    '        self._addr = v\n\n'
    'print(Email("a@b.com").addr)\n'
    'try: Email("bad")\n'
    'except ValueError as e: print("raised:", e)')
code('# C4 — Password with staticmethod validator\n'
    'class Password:\n'
    '    def __init__(self, pw): self.pw = pw\n'
    '    @staticmethod\n'
    '    def is_strong(pw): return len(pw) >= 8\n'
    '    @property\n'
    '    def pw(self): return self._pw\n'
    '    @pw.setter\n'
    '    def pw(self, v):\n'
    '        if not Password.is_strong(v): raise ValueError("too weak")\n'
    '        self._pw = v\n\n'
    'Password("longenough")\n'
    'try: Password("short")\n'
    'except ValueError as e: print("raised:", e)')
code('# C5 — Widget instance counter\n'
    'class Widget:\n'
    '    count = 0\n'
    '    def __init__(self): Widget.count += 1\n'
    '    @classmethod\n'
    '    def total(cls): return cls.count\n\n'
    'Widget(); Widget()\n'
    'print(Widget.total())                 # 2')
code('# C6 — Angle two-way degrees<->radians\n'
    'import math\n'
    'class Angle:\n'
    '    def __init__(self, degrees=0): self._degrees = degrees\n'
    '    @property\n'
    '    def degrees(self): return self._degrees\n'
    '    @degrees.setter\n'
    '    def degrees(self, v): self._degrees = v\n'
    '    @property\n'
    '    def radians(self): return math.radians(self._degrees)\n'
    '    @radians.setter\n'
    '    def radians(self, v): self._degrees = math.degrees(v)\n\n'
    'a = Angle(180); print(round(a.radians, 5))   # 3.14159\n'
    'a.radians = math.pi / 2; print(a.degrees)    # 90.0')
code('# C7 — Vec: slots + magnitude property + from_tuple + repr\n'
    'class Vec:\n'
    '    __slots__ = ("x", "y")\n'
    '    def __init__(self, x, y): self.x = x; self.y = y\n'
    '    @property\n'
    '    def magnitude(self): return (self.x**2 + self.y**2) ** 0.5\n'
    '    @classmethod\n'
    '    def from_tuple(cls, t): return cls(*t)\n'
    '    def __repr__(self): return f"Vec({self.x}, {self.y})"\n\n'
    'print(Vec(3, 4).magnitude, Vec.from_tuple((1, 2)))   # 5.0 Vec(1, 2)')
code('# C8 — cached_property: expensive value computed once\n'
    'from functools import cached_property\n'
    'class Dataset:\n'
    '    def __init__(self, data): self.data = data; self.compute_calls = 0\n'
    '    @cached_property\n'
    '    def stats(self):\n'
    '        self.compute_calls += 1\n'
    '        return {"count": len(self.data), "sum": sum(self.data)}\n\n'
    'ds = Dataset([1, 2, 3])\n'
    'ds.stats; ds.stats\n'
    'print(ds.stats, "| computed", ds.compute_calls, "time(s)")   # ... computed 1 time(s)')

nb = new_notebook(cells=cells)
nb.metadata["kernelspec"] = {"display_name": "Python 3", "language": "python", "name": "python3"}
nb.metadata["language_info"] = {"name": "python"}
nbf.write(nb, "solutions.ipynb")
print("wrote solutions.ipynb with", len(cells), "cells")
